import { randomUUID } from "node:crypto";

import { db } from "@/lib/db";
import {
  invernadas,
} from "@/lib/db/schema";
import { isUniqueViolation } from "@/lib/api/dbErrors";
import {
  toInvernada,
} from "@/lib/api/mappers";
import { __throwOnBrowser } from "@/lib/api/utils/throwOnBrowser";

import {
  sanitizeBoundary,
  type InvalidBoundary,
} from "../_shared/boundary";

import type { RepositoryType } from "@/lib/api/@types/repoTypes";
import type {
  Invernada,
} from "@/lib/types";

/** New physical pasture fields (the id is generated by the server). */
export interface NewInvernadaInput {
  code: string;
  name?: string;
  grass: string;
  hectares: number;
  boundary?: [number, number][];
}

export type InvernadaWriteError =
  | InvalidBoundary
  | "duplicate_code"
  | "invalid_code"
  | "invalid_grass"
  | "invalid_name";

interface AddInvernadaUseCaseProps {
  farmId: number;
  input: NewInvernadaInput;
}

type AddInvernadaUseCaseResponse = Invernada | InvernadaWriteError;

type CurrUseCase = _UseCase<AddInvernadaUseCaseProps, AddInvernadaUseCaseResponse>;

/** Creates one farm-scoped physical invernada. */
export class AddInvernadaUseCase implements CurrUseCase {
  private repository: RepositoryType;

  constructor(repo: RepositoryType = db) {
    __throwOnBrowser("AddInvernadaUseCase.constructor");
    this.repository = repo;
  }

  public run: CurrUseCase["run"] = async ({ farmId, input }) => {
    const code = input.code.trim();
    const name = input.name?.trim();
    const grass = input.grass.trim();
    if (!code || code.toUpperCase().startsWith("LEGACY-")) return "invalid_code";
    if (!grass) return "invalid_grass";
    if (input.name !== undefined && !name) return "invalid_name";

    let boundary: [number, number][] | undefined;
    if (input.boundary !== undefined) {
      const sanitized = sanitizeBoundary(input.boundary);
      if (sanitized === "invalid") return "invalid_boundary";
      boundary = sanitized;
    }

    try {
      const [row] = await this.repository
        .insert(invernadas)
        .values({
          id: randomUUID(),
          farmId,
          code,
          name,
          grass,
          hectares: input.hectares,
          boundary,
        })
        .returning();
      return toInvernada(row);
    } catch (error) {
      if (isUniqueViolation(error)) return "duplicate_code";
      throw error;
    }
  };
}
